apiVersion: apps/v1
kind: Deployment
metadata:
  name: kan-former-deployment
  labels:
    app: kan-former
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kan-former
  template:
    metadata:
      labels:
        app: kan-former
    spec:
      containers:
      - name: kan-former
        image: "<aws_account_id>.dkr.ecr.<region>.amazonaws.com/kan-former:latest"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1024Mi"
        env:
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: kan-former-config
              key: aws_bucket
